development:
  bucket: app-songs-development
  key: AKIAJ6PXZ7USNNIKTG6Q
  secret: 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

test:
  bucket: app-songs-test
  key: AKIAJ6PXZ7USNNIKTG6Q
  secret: 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

edge:
  bucket: app-songs-edge
  key: AKIAJ6PXZ7USNNIKTG6Q
  secret: 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
  
production:
  bucket: app-songs-production
  key: AKIAJ6PXZ7USNNIKTG6Q
  secret: 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