require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LyricsController do

  def mock_lyric(stubs={})
    @mock_lyric ||= mock_model(Lyric, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lyrics as @lyrics" do
      Lyric.stub(:all) { [mock_lyric] }
      get :index
      assigns(:lyrics).should eq([mock_lyric])
    end
  end

  describe "GET show" do
    it "assigns the requested lyric as @lyric" do
      Lyric.stub(:find).with("37") { mock_lyric }
      get :show, :id => "37"
      assigns(:lyric).should be(mock_lyric)
    end
  end

  describe "GET new" do
    it "assigns a new lyric as @lyric" do
      Lyric.stub(:new) { mock_lyric }
      get :new
      assigns(:lyric).should be(mock_lyric)
    end
  end

  describe "GET edit" do
    it "assigns the requested lyric as @lyric" do
      Lyric.stub(:find).with("37") { mock_lyric }
      get :edit, :id => "37"
      assigns(:lyric).should be(mock_lyric)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lyric as @lyric" do
        Lyric.stub(:new).with({'these' => 'params'}) { mock_lyric(:save => true) }
        post :create, :lyric => {'these' => 'params'}
        assigns(:lyric).should be(mock_lyric)
      end

      it "redirects to the created lyric" do
        Lyric.stub(:new) { mock_lyric(:save => true) }
        post :create, :lyric => {}
        response.should redirect_to(lyric_url(mock_lyric))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lyric as @lyric" do
        Lyric.stub(:new).with({'these' => 'params'}) { mock_lyric(:save => false) }
        post :create, :lyric => {'these' => 'params'}
        assigns(:lyric).should be(mock_lyric)
      end

      it "re-renders the 'new' template" do
        Lyric.stub(:new) { mock_lyric(:save => false) }
        post :create, :lyric => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lyric" do
        Lyric.stub(:find).with("37") { mock_lyric }
        mock_lyric.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lyric => {'these' => 'params'}
      end

      it "assigns the requested lyric as @lyric" do
        Lyric.stub(:find) { mock_lyric(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lyric).should be(mock_lyric)
      end

      it "redirects to the lyric" do
        Lyric.stub(:find) { mock_lyric(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lyric_url(mock_lyric))
      end
    end

    describe "with invalid params" do
      it "assigns the lyric as @lyric" do
        Lyric.stub(:find) { mock_lyric(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lyric).should be(mock_lyric)
      end

      it "re-renders the 'edit' template" do
        Lyric.stub(:find) { mock_lyric(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lyric" do
      Lyric.stub(:find).with("37") { mock_lyric }
      mock_lyric.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lyrics list" do
      Lyric.stub(:find) { mock_lyric }
      delete :destroy, :id => "1"
      response.should redirect_to(lyrics_url)
    end
  end

end
